#!/usr/bin/env bash
# CalFlow one-line installer (v2.0).
#
# Bootstraps a CalFlow install at ~/.calflow and registers a `calflow`
# CLI shim at ~/.local/bin/calflow.
#
# Usage (after cloning the repo to a working location):
#     bash scripts/install.sh
#
# Or for a fresh machine:
#     curl -fsSL https://raw.githubusercontent.com/<you>/calflow/main/scripts/install.sh | bash
#
# What it does:
#   1. clones (or refreshes) the repo into ~/.calflow
#   2. creates a venv and installs requirements
#   3. writes ~/.local/bin/calflow shim that activates the venv and runs
#      `python -m cli.main "$@"` from the install dir
#   4. ensures ~/.local/bin is on PATH (writes to ~/.zshrc if missing)

set -e

REPO_URL="${CALFLOW_REPO:-https://github.com/fpenguin/calflow.git}"
INSTALL_DIR="$HOME/.calflow"

echo "🚀 Installing CalFlow..."

# --- confirm overwrite ----------------------------------------------------
if [ -d "$INSTALL_DIR" ]; then
  echo "⚠️  Existing installation found at $INSTALL_DIR"
  read -r -p "Reinstall and overwrite? [y/N]: " confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "❌ Installation cancelled."
    exit 1
  fi
  rm -rf "$INSTALL_DIR"
fi

# --- clone ----------------------------------------------------------------
echo "📦 Fetching repository..."
git clone "$REPO_URL" "$INSTALL_DIR"
cd "$INSTALL_DIR"

# --- venv + deps ----------------------------------------------------------
echo "🐍 Creating virtualenv..."
python3 -m venv .venv
# shellcheck disable=SC1091
source .venv/bin/activate

echo "📦 Installing dependencies..."
pip install --upgrade pip
pip install -r requirements.txt

mkdir -p data secrets

# --- CLI shim -------------------------------------------------------------
echo "🔧 Creating CLI shim..."
mkdir -p "$HOME/.local/bin"

cat > "$HOME/.local/bin/calflow" <<EOF
#!/usr/bin/env bash
# Auto-generated by CalFlow installer.
# Activates the project venv and forwards to \`python -m cli.main\`.

# shellcheck disable=SC1091
source "$INSTALL_DIR/.venv/bin/activate"
cd "$INSTALL_DIR"
exec python3 -m cli.main "\$@"
EOF
chmod +x "$HOME/.local/bin/calflow"

# --- PATH hint ------------------------------------------------------------
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  if [ -f "$HOME/.zshrc" ]; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.zshrc"
    echo "ℹ️  Added ~/.local/bin to PATH in ~/.zshrc"
    echo "   Reload your shell:  source ~/.zshrc"
  else
    echo "ℹ️  Add this to your shell profile so 'calflow' is on PATH:"
    echo '       export PATH="$HOME/.local/bin:$PATH"'
  fi
fi

cat <<EOF

✅ CalFlow installed at: $INSTALL_DIR

Next:
   calflow setup       # OAuth + calendar selection + daemon install
   calflow status      # check daemon
   calflow             # run one cycle now (also what launchd calls)

Interactive REPL (no daemon needed):
   cd "$INSTALL_DIR" && python3 -m cli.repl
EOF
